### ISSUE TITLE
[FR]: Support bzlmod

### ISSUE THREAD

**Issue by kyleconroy** [aspect-build/rules_esbuild#107]
### Describe the feature

I'm not sure if these rules support bzlmod. If they do, could you update the documentation with instructions on how to use it similar to [rules_js](https://github.com/aspect-build/rules_js/releases/tag/v1.13.0)?

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by alexeagle** [comment]
I started this here: https://github.com/aspect-build/rules_esbuild/compare/bzlmod

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/394

**Comment by alexeagle** [comment]
https://registry.bazel.build/modules/aspect_rules_esbuild
