### ISSUE TITLE
[Bug/FR]: format is ignored unless splitting is set to True

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_esbuild#111]
### What happened?

Given this:

```bazel
esbuild(
    name = "bundle",
    entry_points = ["src.js"],
    srcs = ["src",],
    platform = "browser",
    format = "esm",
)
```

I would expect the output to be an ESM bundle for the browser. However, to get that either `entry_points` needs to be changed to `entry_point`, _or_ `splitting = True` needs to be set. Without either of those the output is an IIFE. 

Having a look at the `bundle.args.json` file for the above I see that `format` is excluded (which explains why esbuild defaults to IIFE). When I change `entry_points` to `entry_point`, or include `splitting = True` it's in the args, and set to `esm`. I see that the defaults are documented, but it also seems unusual that I have to set `splitting` to true to get anything besides an IIFE given direct use of esbuild allows setting of `format` independently of other properties.

I'm wondering:

1. If `format` is going to be ignored in the case above, is it possible to emit a warning or notice?
2. esbuild used directly allows you to set `format` independently of `platform`, `target`, and whether you're using `entry_point` or `entry_points`. Is that possible here?

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: rules_esbuild-0.13.5

Language(s) and/or frameworks involved: N/A

### How to reproduce

```shell
See above :)
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Aiming for rules_esbuild 1.0 in the near future so will address this as part of that push
