### ISSUE TITLE
[FR]: Support for bundle=false

### ISSUE THREAD

**Issue by josephglanville** [aspect-build/rules_esbuild#97]
### What is the current behavior?

Currently `rules_esbuild` only runs `esbuild` with `bundle=true`.

### Describe the feature

Support `bundle=false` and properly propagate transitive dependencies and sources in this case.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by alexeagle** [comment]
We can verify this is working by swapping out `transpiler = swc` in our examples, I think they have coverage for transitive deps.
